config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "userfiles#index"
  resources :userfiles
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/up', to: proc { [200, {}, ['OK']] }
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/userfile.rb
class Userfile < ApplicationRecord
  has_one_attached :uf_file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/userfiles_controller.rb
class UserfilesController < ApplicationController

  def create
    @userfile = Userfile.new
    @userfile.uf_file.attach(params[:userfile][:uf_file])

    if @userfile.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      render :index
    end
  end

  def index
    @userfiles = Userfile.all
  end

  def new
    @userfile = Userfile.new
  end

  def show
    @userfile = Userfile.find(params[:id])
    redirect_to rails_blob_path(@userfile.uf_file, disposition: "attachment")
  end

end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/userfiles_helper.rb
module UserfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUploadApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/userfiles/_userfile.html.erb
<li>
  <%= link_to "#{userfile.uf_file.filename}", userfile_path(userfile), target: "_blank" %>
</li>

app/views/userfiles/create.turbo_stream.erb
<%= turbo_stream.append "uf-list", partial: "userfiles/userfile", locals: { userfile: @userfile } %>

app/views/userfiles/index.html.erb
<h1>Загрузить файл</h1>
<%= turbo_frame_tag "uf", src: new_userfile_path(@userfile), target: "_top" %>
<h1>Список загруженных файлов</h1>
<div id="uf-list">
  <%= render @userfiles %>
</div>

app/views/userfiles/new.html.erb
<%= turbo_frame_tag "uf", target: "_top" do %>
<%= form_with model: Userfile.new, url: userfiles_path, local: false do |form| %>
    <%= form.file_field :uf_file, direct_upload: true %>
    <br>
    <br>
    <%= form.submit 'Загрузить файл' %>
<% end %>
<% end %>